<?php

namespace App\Model\Table;

use App\Model\Entity\Power;
use Cake\Datasource\EntityInterface;
use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Powers Model
 *
 * @property \App\Model\Table\UsersTable|\Cake\ORM\Association\BelongsTo $CreatedBies
 * @property \App\Model\Table\UsersTable|\Cake\ORM\Association\BelongsTo $UpdatedBies
 * @property \App\Model\Table\CharacterPowersTable|\Cake\ORM\Association\HasMany $CharacterPowers
 * @property \App\Model\Table\TemplatePowersTable|\Cake\ORM\Association\HasMany $TemplatePowers
 *
 * @method Power get($primaryKey, $options = [])
 * @method Power newEntity($data = null, array $options = [])
 * @method Power[] newEntities(array $data, array $options = [])
 * @method Power|bool save(EntityInterface $entity, $options = [])
 * @method Power patchEntity(EntityInterface $entity, array $data, array $options = [])
 * @method Power[] patchEntities($entities, array $data, array $options = [])
 * @method Power findOrCreate($search, callable $callback = null, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class PowersTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('powers');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp', [
            'events' => [
                'Model.beforeSave' => [
                    'created' => 'new',
                    'updated' => 'always',
                ]
            ]
        ]);

        $this->belongsTo('CreatedBy', [
            'foreignKey' => 'created_by_id',
            'joinType' => 'INNER',
            'className' => 'Users'
        ]);
        $this->belongsTo('UpdatedBy', [
            'foreignKey' => 'updated_by_id',
            'joinType' => 'INNER',
            'className' => 'Users'
        ]);
        $this->hasMany('CharacterPowers', [
            'foreignKey' => 'power_id'
        ]);
        $this->hasMany('TemplatePowers', [
            'foreignKey' => 'power_id'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->scalar('power_name')
            ->maxLength('power_name', 45)
            ->requirePresence('power_name', 'create')
            ->notEmpty('power_name')
            ->add('power_name', 'unique', ['rule' => 'validateUnique', 'provider' => 'table']);

        $validator
            ->scalar('description')
            ->allowEmpty('description');

        $validator
            ->requirePresence('cost', 'create')
            ->notEmpty('cost');

        $validator
            ->boolean('is_official')
            ->requirePresence('is_official', 'create')
            ->notEmpty('is_official');

        $validator
            ->boolean('is_approved')
            ->requirePresence('is_approved', 'create')
            ->notEmpty('is_approved');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->isUnique(['power_name']));
        $rules->add($rules->existsIn(['created_by_id'], 'CreatedBy'));
        $rules->add($rules->existsIn(['updated_by_id'], 'UpdatedBy'));

        return $rules;
    }

    protected function _processSave($entity, $options)
    {
        return parent::_processSave($entity, $options); // TODO: Change the autogenerated stub
        var_dump($entity);
    }


}
